Array - Store a group of elements (or values) same datatype (Homegeneous data)\
Numpy_Array - Store a group of elements (or values) different datatype (Heterogeneous data)

Types of Array:
 - Single dimension arrays (or 1D arrays) -> These arrays represent only one row or one column of elements.
 - Multi-dimensional arrays (or 2D,3D arrays etc) -> These arrays represent more than one row and more than column of elements.

In [8]:
import numpy as np
import pandas as pd
#from numpy import *

# 1. A Python program to create a simple array using numpy

In [6]:
array = np.array([10,20,30,40,50])
print(array)

[10 20 30 40 50]


Create array using Numpy Package (or Folder) 
1. array()
2. linspace()
3. arange()
4. zeros() and
5. ones()

# Creating Arrays using array()

In [14]:
arr = array([10.5,20.6,30.5,40.2,50.1],int)
print(arr)

[10 20 30 40 50]


In [16]:
arr1 = array([10,20,30,40,50],float)
print(arr1)

[10. 20. 30. 40. 50.]


In [17]:
arr2 = array([10.5,20,30.5,40.2,50])
print(arr2)

[10.5 20.  30.5 40.2 50. ]


In [18]:
arr3 = array(['a','b','c','d','e'])
print(arr3)

['a' 'b' 'c' 'd' 'e']


In [19]:
type(arr3)

numpy.ndarray

In [21]:
arr4 = array(['Kolkata','Delhi','Mumbai','Bangalore'],dtype=str)
print(arr4)

['Kolkata' 'Delhi' 'Mumbai' 'Bangalore']


In [22]:
type(arr4)

numpy.ndarray

# Creating Arrays using linspace()

linspace(start,stop,n)

In [24]:
a = linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


# Creating Arrays using logspace()

logspace(start,end,n)

In [29]:
a = logspace(1,4,5) # 10 ** 1 to 10 ** 4
print(a)

[   10.            56.23413252   316.22776602  1778.27941004
 10000.        ]


In [31]:
n = len(a)
for i in range(n):
    print('%.1f' % a[i],end=' ')

10.0 56.2 316.2 1778.3 10000.0 

# Creating Arrays using arange()

arange(start,stop,step)

In [33]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arange(5,10)

array([5, 6, 7, 8, 9])

In [35]:
arange(1,10,3)

array([1, 4, 7])

In [36]:
arange(10,1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [37]:
arange(0,10,1.5)

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [38]:
arange(2,10,2)

array([2, 4, 6, 8])

# Creating Arrays using zeros() and ones()

zeros(n,dtype)\
ones(n,dtype)

In [40]:
zeros(5)

array([0., 0., 0., 0., 0.])

In [41]:
zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [42]:
ones(5)

array([1., 1., 1., 1., 1.])

In [43]:
ones(5,dtype=int)

array([1, 1, 1, 1, 1])

# Mathematical Operations on Arrays

Vectorized Operations: 
 - They are operations that are applied to an entire array (or a subset of it) in a single operation, 
rather than looping through each element individually.
 - Vectorized Operations are faster
 - Vectorized Operations are syntactical clear.

https://numpy.org/doc/stable/reference/routines.math.html

In [44]:
arr

array([10, 20, 30, 40, 50])

In [46]:
# Addition
arr + 5

array([15, 25, 35, 45, 55])

In [47]:
# Substraction
arr - 10

array([ 0, 10, 20, 30, 40])

In [50]:
# Production 
arr * 3

array([ 30,  60,  90, 120, 150])

In [49]:
# Division
arr / 4

array([ 2.5,  5. ,  7.5, 10. , 12.5])

In [51]:
# Exponential
arr ** 2

array([ 100,  400,  900, 1600, 2500])

In [53]:
sin(arr)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [54]:
log(arr)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [55]:
cos(arr)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [56]:
sum(arr)

150

# Indexing and Slicing in numpy Arrays

In [62]:
a = arange(1,30,2)
print(a)
print()
print(a[2:5])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]

[5 7 9]


# Dimensions of Arrays

In [67]:
arr_1d = array([10,20,33,30])
arr_2d = array([[1,3,4],[4,6,7],[6,3,4]])
arr_3d = array([[[1,2,3],[2,3,1]],[[4,8,9],[7,0,6]]])
print(arr_1d)
print()
print(arr_2d)
print()

print(arr_3d)

[10 20 33 30]

[[1 3 4]
 [4 6 7]
 [6 3 4]]

[[[1 2 3]
  [2 3 1]]

 [[4 8 9]
  [7 0 6]]]


# Attributes of an Array

-  numpy array class is called ndarray
-  ndim()
-  shape() -> no of dimensions,row,column
-  size() -> Total no of elements in the array
-  itemsize() -> Memory Size of the array element in bytes
-  dtype
-  nbytes
-  reshape()
-  flatten() -> convert 2D array to 1D array

In [68]:
ndim(arr_3d)

3

In [69]:
ndim(arr_1d)

1

In [70]:
ndim(arr_2d)

2

In [71]:
shape(arr_1d)

(4,)

In [72]:
shape(arr_2d)

(3, 3)

In [73]:
shape(arr_3d)

(2, 2, 3)

In [74]:
size(arr_1d)

4

In [75]:
size(arr_2d)

9

In [76]:
size(arr_3d)

12

In [77]:
arr_1d.itemsize

8

In [78]:
arr_3d.itemsize

8

In [79]:
arr_1d.dtype

dtype('int64')

In [80]:
arr_1d

array([10, 20, 33, 30])

In [81]:
arr_2d.dtype

dtype('int64')

In [82]:
arr_1d.nbytes

32

In [83]:
arr_3d.nbytes

96

In [87]:
arr_1d.shape

(4,)

In [88]:
arr_1d

array([10, 20, 33, 30])

In [89]:
arr_1d.reshape(2,2)

array([[10, 20],
       [33, 30]])

In [90]:
arr_1d.reshape(1,-1)

array([[10, 20, 33, 30]])

array([[10, 20],
       [33, 30]])

In [92]:
arr_2d.flatten()

array([1, 3, 4, 4, 6, 7, 6, 3, 4])

In [93]:
arr_3d.flatten()

array([1, 2, 3, 2, 3, 1, 4, 8, 9, 7, 0, 6])

# Working with Multi-Dimensional Arrays

Create Multi-Dimensional Arrays 
- array()
- zeros()
- ones()
- eye()
- reshape()

In [97]:
a = array([[1,2,3,4,5],[6,7,8,9,10]],int)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


zeros((r,c),dtype)\
ones((r,c),dtype)

In [98]:
zeros((4,3),int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [99]:
ones((3,5),float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

eye(n,dtype) -> n no of row and column

In [100]:
eye(5,dtype=float)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Indexing and Slicing in Multi-Dimensional Arrays

In [101]:
arr_2d

array([[1, 3, 4],
       [4, 6, 7],
       [6, 3, 4]])

In [102]:
arr_2d[1][2]

7

In [105]:
for i in range(len(arr_2d)):
    for j in range(len(arr_2d[i])):
        print(arr_2d[i][j],end=' ')

1 3 4 4 6 7 6 3 4 

# A Python Program to retrieve the elements from a 3D array

In [106]:
# Create 3D array
arr3d = array([[[1,2,3],[3,4,5]],[[12,13,14],[20,30,12]],[[22,34,25],[45,42,14]]])
print(arr3d)

[[[ 1  2  3]
  [ 3  4  5]]

 [[12 13 14]
  [20 30 12]]

 [[22 34 25]
  [45 42 14]]]


In [110]:
for i in range(len(arr3d)):
    for j in range(len(arr3d[i])):
        for k in range(len(arr3d[i][j])):
            print(arr3d[i][j][k],end = '\t')
        print()
    print()

1	2	3	
3	4	5	

12	13	14	
20	30	12	

22	34	25	
45	42	14	



# Slicing Multi-Dimensional Arrays

In [116]:
a = arange(11,36,1).reshape(5,5)
print(a)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [117]:
a[0]

array([11, 12, 13, 14, 15])

In [120]:
a[0,:]

array([11, 12, 13, 14, 15])

In [121]:
a[1]

array([16, 17, 18, 19, 20])

In [122]:
a[1,:]

array([16, 17, 18, 19, 20])

In [130]:
a[0:5,1:2] # Retrieve all rows with 1st column

array([[12],
       [17],
       [22],
       [27],
       [32]])

In [131]:
a[0:2,0:3] # Retrieve 0th row to 1st row with columns from 0th column to 2nd column

array([[11, 12, 13],
       [16, 17, 18]])

In [132]:
a[:2,:3]

array([[11, 12, 13],
       [16, 17, 18]])

In [134]:
a[2:4,3:] # Retrieve 2nd and 3rd rows with 3rd column and 4th columns

array([[24, 25],
       [29, 30]])

In [135]:
a[2:4,3:5]

array([[24, 25],
       [29, 30]])

# Matrices in numpy

- Rectangular Array
- row x column
- If matrix has only one row called Row Matrix
- If matrix has only one column called Column Matrix
- m x n called matrix
- 2 x 3 means 2 rows and 3 columns
- matrix(2D array or string)

In [139]:
matrix_1 = matrix(arr_2d)
print(matrix_1)

[[1 3 4]
 [4 6 7]
 [6 3 4]]


In [141]:
matrix_2 = matrix("1,2;3,4")
print(matrix_2)

[[1 2]
 [3 4]]


# Getting Diagonal Elements of a Matrix

- diagonal(matrix)

In [143]:
matrix_1

matrix([[1, 3, 4],
        [4, 6, 7],
        [6, 3, 4]])

In [144]:
diagonal(matrix_1)

array([1, 6, 4])

# Finding Maximum and Minimum Elements

In [145]:
arr_3d

array([[[1, 2, 3],
        [2, 3, 1]],

       [[4, 8, 9],
        [7, 0, 6]]])

In [147]:
arr_3d.max()

9

In [148]:
arr_3d.min()

0

# Finding Sum and Average Elements

In [149]:
arr_3d.sum()

46

In [150]:
arr_3d.mean()

3.8333333333333335

# Products of Elements

In [152]:
arr_2d.prod()

145152

In [153]:
arr_2d

array([[1, 3, 4],
       [4, 6, 7],
       [6, 3, 4]])

In [154]:
arr_2d.prod(1)

array([ 12, 168,  72])

# Sorting the Matrix

In [156]:
matrix_1

matrix([[1, 3, 4],
        [4, 6, 7],
        [6, 3, 4]])

In [163]:
sort(matrix_1,axis=0) # column wise

matrix([[1, 3, 4],
        [4, 3, 4],
        [6, 6, 7]])

In [164]:
sort(arr_2d,axis=1) # row wise

array([[1, 3, 4],
       [4, 6, 7],
       [3, 4, 6]])

# Transpose of a Matrix

In [167]:
matrix_1

matrix([[1, 3, 4],
        [4, 6, 7],
        [6, 3, 4]])

In [168]:
transpose(matrix_1)

matrix([[1, 4, 6],
        [3, 6, 3],
        [4, 7, 4]])

In [170]:
matrix_1.T

matrix([[1, 4, 6],
        [3, 6, 3],
        [4, 7, 4]])

In [171]:
matrix_1.getT()

matrix([[1, 4, 6],
        [3, 6, 3],
        [4, 7, 4]])

# Matrix Addition and Multiplication

In [173]:
matrix_1

matrix([[1, 3, 4],
        [4, 6, 7],
        [6, 3, 4]])

In [174]:
matrix_2

matrix([[1, 2],
        [3, 4]])

In [177]:
arr_2d

array([[1, 3, 4],
       [4, 6, 7],
       [3, 4, 6]])

In [176]:
matrix_1 + arr_2d

matrix([[ 2,  6,  8],
        [ 8, 12, 14],
        [ 9,  7, 10]])

In [178]:
matrix_1 * arr_2d

matrix([[ 25,  37,  49],
        [ 49,  76, 100],
        [ 30,  52,  69]])

# Random Numbers

In [186]:
rand_num = random.randint(5,10)
print(rand_num)

9


In [183]:
random.rand()

0.3354347077514681

In [184]:
random.rand(5)

array([0.77423284, 0.07091839, 0.15789178, 0.77189526, 0.11167377])

In [185]:
random.rand(2,3)

array([[0.78302267, 0.56135851, 0.51429373],
       [0.86338538, 0.82437362, 0.77273085]])

In [187]:
random.sample(20)

array([0.13374028, 0.51074352, 0.38461611, 0.15365473, 0.13665777,
       0.24506144, 0.09190173, 0.04485552, 0.53331514, 0.49826882,
       0.00349954, 0.15845039, 0.85291271, 0.65994557, 0.80313479,
       0.55519293, 0.46097003, 0.96245744, 0.4363473 , 0.96923947])